#!/usr/bin/env bash
# start, restart and stop the manage_my_process process
# shellcheck disable=SC2086
pid="$(pgrep -f ./manage_my_process)"
case "$1" in
  start)
    ./manage_my_process &
	sudo touch /var/run/my_process.pid
    echo "$pid" > "/var/run/my_process.pid"
    echo "manage_my_process started"
    ;;
  stop)
    kill "$pid"
    sudo rm -rf /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    kill "$pid"
    sudo rm -rf /var/run/my_process.pid
    ./manage_my_process &
    echo "$pid" > "/var/run/my_process.pid"
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
